package com.tecnoven.notify.ui;

import java.security.NoSuchAlgorithmException;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import com.tecnoven.notify.domain.UserData;
import com.tecnoven.notify.ui.core.func.ICatalogueObject;
import com.tecnoven.notify.ui.core.func.IFunctDispatch;
import com.tecnoven.notify.util.ConnectionDB;
import com.tecnoven.notify.util.Constants;
import com.tecnoven.notify.util.FileUtil;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChangePasswordFrame.java
 *
 * Created on Jan 29, 2010, 12:39:23 AM
 */

/**
 * 
 * @author hector
 */
public class ChangePasswordDialog extends javax.swing.JDialog  implements IFunctDispatch{

	private UserData userLogged;
	/**
	 * 
	 */
	private static final long serialVersionUID = 900469713615063750L;

	/** Creates new form ChangePasswordFrame */
	public ChangePasswordDialog() {
		super();
		this.setTitle("Cambio de Clave");
		initComponents();
		setResizable(false);
		setModal(true);
	}

	public ChangePasswordDialog(UserData user) {
		this();
		this.userLogged = user;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPasswordField1 = new javax.swing.JPasswordField();
		jPasswordField2 = new javax.swing.JPasswordField();

		jLabel1.setText("Nueva Clave");

		jLabel2.setText("Confirmar Nueva Clave");

		jButton1.setText("Aceptar");
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
		Constants.PATH_TO_ICONS + "ok.png")));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Cancelar");
		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
		Constants.PATH_TO_ICONS + "cancel.png")));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(29, 29, 29)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel2)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jPasswordField2)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																257,
																Short.MAX_VALUE))
										.addContainerGap(14, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										165, Short.MAX_VALUE).addComponent(
										jButton1).addGap(30, 30, 30)
										.addComponent(jButton2).addGap(159,
												159, 159)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(28, 28, 28)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jPasswordField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												29, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		this.jButton1.setEnabled(false);
		String pass1 = String.valueOf(jPasswordField1.getPassword());
		String pass2 = String.valueOf(jPasswordField2.getPassword());
		String pwdLogged;
		try {
			pwdLogged = FileUtil.getHashValue(pass1);
			if (pass1.equals(pass2) && (!pwdLogged.equals(this.userLogged.getPassword()))) {
				SwingUtilities.invokeLater(new Runnable() {
					@Override
					public void run() {
						try {
							action();
						} catch (NoSuchAlgorithmException e) {
						}
					}
				});
			} else {
				this.jButton1.setEnabled(true);
				JOptionPane.showConfirmDialog(this, "Clave Inválida",
						"Error", JOptionPane.DEFAULT_OPTION,
						JOptionPane.ERROR_MESSAGE);
				this.jPasswordField1.setText("");
				this.jPasswordField2.setText("");
				this.jPasswordField1.requestFocus();
			}
		} catch (NoSuchAlgorithmException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void action() throws NoSuchAlgorithmException {
		this.userLogged.setLogged(true);
		this.userLogged.setPassword(FileUtil.getHashValue(String
				.valueOf(jPasswordField1.getPassword())));
		ConnectionDB.getInstance().getSession().update(this.userLogged);
		ConnectionDB.getInstance().getSession().flush();
		JOptionPane.showConfirmDialog(this, "Su clave ha sido actualizada",
				"Informaci\u00f3n", JOptionPane.DEFAULT_OPTION,
				JOptionPane.INFORMATION_MESSAGE);
		setVisible(false);
		dispose();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		this.setVisible(false);
		this.dispose();
	}// GEN-LAST:event_jButton2ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	// End of variables declaration//GEN-END:variables

	@Override
	public void cancel() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void initState() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void ok() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setCatalogObject(ICatalogueObject object) {
		// TODO Auto-generated method stub
		
	}

}
