/*
 * MainPanelDispatch.java
 *
 * Created on May 18, 2009, 2:44 AM
 */

package com.tecnoven.notify.ui;

import com.tecnoven.notify.ui.core.func.ICatalogueObject;
import com.tecnoven.notify.ui.core.func.IFunctDispatch;

/**
 *
 * @author  hector
 */
public class MainPanelDispatch extends javax.swing.JPanel implements IFunctDispatch{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 6378144323477959175L;

	/** Creates new form MainPanelDispatch */
    public MainPanelDispatch() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

	public void cancel() {
		// TODO Auto-generated method stub
		
	}

	public void initState() {
		// TODO Auto-generated method stub
		
	}

	public void ok() {
		// TODO Auto-generated method stub
		
	}

	public void setCatalogObject(ICatalogueObject object) {
		// TODO Auto-generated method stub
		
	}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
